config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :permissions
  resources :roles
  resources :users
  resources :categories
  root 'categories#index'

end

app/models/permission.rb
class Permission < ActiveRecord::Base
	belongs_to :user
	belongs_to :role
	validates_presence_of :user_id, :role_id
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!,except: [:index, :show]
   # this is to check if the action is made available to user
   load_and_authorize_resource
  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    # abort params.inspect
    params[:permission][:role_id] = params[:permission][:role_id][0]
    # abort params[:permission][:role_id][0].inspect
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:user_id, :role_id)
    end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_for(@permission) do |f| %>
  <% if @permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% @permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :role_id %><br>
    <%= f.number_field :role_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form' %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Permissions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= permission.user_id %></td>
        <td><%= permission.role_id %></td>
        <td><%= link_to 'Show', permission %></td>
        <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
        <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form' %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @permission.user_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @permission.role_id %>
</p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>